import type { City } from "@/components/features/philippines-map";

// City data with coordinates and static counts
const citiesData: City[] = [
  {
    id: "quezon-city",
    name: "Quezon",
    latitude: 14.676,
    longitude: 121.0437,
    description: "Metro Manila - Largest city in Metro Manila",
    spotted: 474,
  },
  {
    id: "makati",
    name: "Makati",
    latitude: 14.5547,
    longitude: 121.0244,
    description: "Metro Manila - Business district",
    spotted: 249,
  },
  {
    id: "manila",
    name: "Manila",
    latitude: 14.5995,
    longitude: 120.9842,
    description: "Capital city of the Philippines",
    spotted: 241,
  },
  {
    id: "taguig",
    name: "Taguig",
    latitude: 14.5176,
    longitude: 121.0509,
    description: "Metro Manila - BGC area",
    spotted: 240,
  },
  {
    id: "tagaytay",
    name: "Tagaytay",
    latitude: 14.1003,
    longitude: 120.9332,
    description: "Cavite - Popular tourist destination",
    spotted: 178,
  },
  {
    id: "marikina",
    name: "Marikina",
    latitude: 14.6507,
    longitude: 121.1029,
    description: "Metro Manila - Shoe capital",
    spotted: 156,
  },
  {
    id: "pasay",
    name: "Pasay",
    latitude: 14.5378,
    longitude: 121.0014,
    description: "Metro Manila",
    spotted: 118,
  },
  {
    id: "caloocan",
    name: "Caloocan",
    latitude: 14.6546,
    longitude: 120.9842,
    description: "Metro Manila",
    spotted: 101,
  },
  {
    id: "valenzuela",
    name: "Valenzuela",
    latitude: 14.7004,
    longitude: 120.983,
    description: "Metro Manila",
    spotted: 100,
  },
  {
    id: "baguio",
    name: "Baguio",
    latitude: 16.4023,
    longitude: 120.596,
    description: "Benguet - Summer capital of the Philippines",
    spotted: 98,
  },
  {
    id: "mandaluyong",
    name: "Mandaluyong",
    latitude: 14.5794,
    longitude: 121.0359,
    description: "Metro Manila",
    spotted: 92,
  },
  {
    id: "trece-martires",
    name: "Trece Martires",
    latitude: 14.2833,
    longitude: 120.8667,
    description: "Cavite - Capital of Cavite province",
    spotted: 81,
  },
  {
    id: "paranaque",
    name: "Parañaque",
    latitude: 14.4793,
    longitude: 121.0198,
    description: "Metro Manila",
    spotted: 78,
  },
  {
    id: "pasig",
    name: "Pasig",
    latitude: 14.5764,
    longitude: 121.0851,
    description: "Metro Manila",
    spotted: 78,
  },
  {
    id: "indang",
    name: "Indang",
    latitude: 14.1986,
    longitude: 120.8767,
    description: "Cavite",
    spotted: 56,
  },
  {
    id: "malabon",
    name: "Malabon",
    latitude: 14.6567,
    longitude: 120.9569,
    description: "Metro Manila",
    spotted: 50,
  },
  {
    id: "silang",
    name: "Silang",
    latitude: 14.2306,
    longitude: 120.9747,
    description: "Cavite",
    spotted: 48,
  },
  {
    id: "dasmariñas",
    name: "Dasmariñas",
    latitude: 14.3294,
    longitude: 120.9367,
    description: "Cavite",
    spotted: 35,
  },
  {
    id: "general-trias",
    name: "General Trias",
    latitude: 14.3869,
    longitude: 120.8811,
    description: "Cavite",
    spotted: 33,
  },
  {
    id: "san-juan",
    name: "San Juan",
    latitude: 14.6019,
    longitude: 121.0355,
    description: "Metro Manila",
    spotted: 25,
  },
  {
    id: "navotas",
    name: "Navotas",
    latitude: 14.6667,
    longitude: 120.95,
    description: "Metro Manila",
    spotted: 21,
  },
  {
    id: "bacoor",
    name: "Bacoor",
    latitude: 14.4564,
    longitude: 120.94,
    description: "Cavite",
    spotted: 19,
  },
  {
    id: "las-pinas",
    name: "Las Piñas",
    latitude: 14.4506,
    longitude: 120.9828,
    description: "Metro Manila",
    spotted: 13,
  },
];

/**
 * Get cities with their spotted counts
 * Returns static data with pre-configured counts
 */
export async function getCitiesWithCounts(): Promise<City[]> {
  return citiesData;
}
